#!/usr/bin/env bash
set -euo pipefail
mkdir -p /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official/paper_artifacts/atari_v21_aux_warmup/run_logs
echo "V21 Stage A started at $(date -Is)"
echo '===== START v21__hts_hier_x3_warmup50k__breakout__seed0 ====='
cd /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official && export CUDA_VISIBLE_DEVICES=5 WANDB_MODE=online WANDB_PROJECT=hts-wm-atari-dev WANDB_GROUP=v21_aux_warmup_breakout WANDB_JOB_TYPE=v21_stage_a_breakout_screen WANDB_TAGS=v21,aux_warmup,warmup50k,locked_hier_x3,atari100k,breakout,no_video WANDB_RUN_NAME=v21__hts_hier_x3_warmup50k__breakout__seed0 XLA_PYTHON_CLIENT_PREALLOCATE=false TMPDIR=/mnt/disk1/backup_user/dat.tt2/xuance/tmp; /mnt/disk1/backup_user/dat.tt2/xuance/.venv/bin/python -m dreamerv3.main_hts --configs hts_atari100k size12m hts_warmup_50k_raw --task atari100k_breakout --seed 0 --logdir /mnt/disk1/backup_user/dat.tt2/xuance/logs/external_baselines/dreamerv3_official_hts_v21_aux_warmup/hts_locked_hier_x3_warmup_50k_raw/breakout/seed_0 --run.steps 110000 --run.envs 1 --run.train_ratio 256 --run.log_every 250 --run.report_every 999999 --run.log_policy_video False --run.save_every 10000 --batch_size 16 --batch_length 64 --agent.hts.l_hier 0.3 --agent.report False --logger.outputs jsonl,scope,wandb --jax.prealloc False --jax.jit True 2>&1 | tee /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official/paper_artifacts/atari_v21_aux_warmup/run_logs/v21__hts_hier_x3_warmup50k__breakout__seed0.log
echo '===== DONE v21__hts_hier_x3_warmup50k__breakout__seed0 ====='
echo '===== START v21__hts_hier_x3_warmup50k__breakout__seed1 ====='
cd /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official && export CUDA_VISIBLE_DEVICES=5 WANDB_MODE=online WANDB_PROJECT=hts-wm-atari-dev WANDB_GROUP=v21_aux_warmup_breakout WANDB_JOB_TYPE=v21_stage_a_breakout_screen WANDB_TAGS=v21,aux_warmup,warmup50k,locked_hier_x3,atari100k,breakout,no_video WANDB_RUN_NAME=v21__hts_hier_x3_warmup50k__breakout__seed1 XLA_PYTHON_CLIENT_PREALLOCATE=false TMPDIR=/mnt/disk1/backup_user/dat.tt2/xuance/tmp; /mnt/disk1/backup_user/dat.tt2/xuance/.venv/bin/python -m dreamerv3.main_hts --configs hts_atari100k size12m hts_warmup_50k_raw --task atari100k_breakout --seed 1 --logdir /mnt/disk1/backup_user/dat.tt2/xuance/logs/external_baselines/dreamerv3_official_hts_v21_aux_warmup/hts_locked_hier_x3_warmup_50k_raw/breakout/seed_1 --run.steps 110000 --run.envs 1 --run.train_ratio 256 --run.log_every 250 --run.report_every 999999 --run.log_policy_video False --run.save_every 10000 --batch_size 16 --batch_length 64 --agent.hts.l_hier 0.3 --agent.report False --logger.outputs jsonl,scope,wandb --jax.prealloc False --jax.jit True 2>&1 | tee /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official/paper_artifacts/atari_v21_aux_warmup/run_logs/v21__hts_hier_x3_warmup50k__breakout__seed1.log
echo '===== DONE v21__hts_hier_x3_warmup50k__breakout__seed1 ====='
echo '===== START v21__hts_hier_x3_warmup50k__breakout__seed2 ====='
cd /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official && export CUDA_VISIBLE_DEVICES=5 WANDB_MODE=online WANDB_PROJECT=hts-wm-atari-dev WANDB_GROUP=v21_aux_warmup_breakout WANDB_JOB_TYPE=v21_stage_a_breakout_screen WANDB_TAGS=v21,aux_warmup,warmup50k,locked_hier_x3,atari100k,breakout,no_video WANDB_RUN_NAME=v21__hts_hier_x3_warmup50k__breakout__seed2 XLA_PYTHON_CLIENT_PREALLOCATE=false TMPDIR=/mnt/disk1/backup_user/dat.tt2/xuance/tmp; /mnt/disk1/backup_user/dat.tt2/xuance/.venv/bin/python -m dreamerv3.main_hts --configs hts_atari100k size12m hts_warmup_50k_raw --task atari100k_breakout --seed 2 --logdir /mnt/disk1/backup_user/dat.tt2/xuance/logs/external_baselines/dreamerv3_official_hts_v21_aux_warmup/hts_locked_hier_x3_warmup_50k_raw/breakout/seed_2 --run.steps 110000 --run.envs 1 --run.train_ratio 256 --run.log_every 250 --run.report_every 999999 --run.log_policy_video False --run.save_every 10000 --batch_size 16 --batch_length 64 --agent.hts.l_hier 0.3 --agent.report False --logger.outputs jsonl,scope,wandb --jax.prealloc False --jax.jit True 2>&1 | tee /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official/paper_artifacts/atari_v21_aux_warmup/run_logs/v21__hts_hier_x3_warmup50k__breakout__seed2.log
echo '===== DONE v21__hts_hier_x3_warmup50k__breakout__seed2 ====='
echo '===== START v21__hts_hier_x3_warmup100k__breakout__seed0 ====='
cd /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official && export CUDA_VISIBLE_DEVICES=5 WANDB_MODE=online WANDB_PROJECT=hts-wm-atari-dev WANDB_GROUP=v21_aux_warmup_breakout WANDB_JOB_TYPE=v21_stage_a_breakout_screen WANDB_TAGS=v21,aux_warmup,warmup100k,locked_hier_x3,atari100k,breakout,no_video WANDB_RUN_NAME=v21__hts_hier_x3_warmup100k__breakout__seed0 XLA_PYTHON_CLIENT_PREALLOCATE=false TMPDIR=/mnt/disk1/backup_user/dat.tt2/xuance/tmp; /mnt/disk1/backup_user/dat.tt2/xuance/.venv/bin/python -m dreamerv3.main_hts --configs hts_atari100k size12m hts_warmup_100k_raw --task atari100k_breakout --seed 0 --logdir /mnt/disk1/backup_user/dat.tt2/xuance/logs/external_baselines/dreamerv3_official_hts_v21_aux_warmup/hts_locked_hier_x3_warmup_100k_raw/breakout/seed_0 --run.steps 110000 --run.envs 1 --run.train_ratio 256 --run.log_every 250 --run.report_every 999999 --run.log_policy_video False --run.save_every 10000 --batch_size 16 --batch_length 64 --agent.hts.l_hier 0.3 --agent.report False --logger.outputs jsonl,scope,wandb --jax.prealloc False --jax.jit True 2>&1 | tee /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official/paper_artifacts/atari_v21_aux_warmup/run_logs/v21__hts_hier_x3_warmup100k__breakout__seed0.log
echo '===== DONE v21__hts_hier_x3_warmup100k__breakout__seed0 ====='
echo '===== START v21__hts_hier_x3_warmup100k__breakout__seed1 ====='
cd /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official && export CUDA_VISIBLE_DEVICES=5 WANDB_MODE=online WANDB_PROJECT=hts-wm-atari-dev WANDB_GROUP=v21_aux_warmup_breakout WANDB_JOB_TYPE=v21_stage_a_breakout_screen WANDB_TAGS=v21,aux_warmup,warmup100k,locked_hier_x3,atari100k,breakout,no_video WANDB_RUN_NAME=v21__hts_hier_x3_warmup100k__breakout__seed1 XLA_PYTHON_CLIENT_PREALLOCATE=false TMPDIR=/mnt/disk1/backup_user/dat.tt2/xuance/tmp; /mnt/disk1/backup_user/dat.tt2/xuance/.venv/bin/python -m dreamerv3.main_hts --configs hts_atari100k size12m hts_warmup_100k_raw --task atari100k_breakout --seed 1 --logdir /mnt/disk1/backup_user/dat.tt2/xuance/logs/external_baselines/dreamerv3_official_hts_v21_aux_warmup/hts_locked_hier_x3_warmup_100k_raw/breakout/seed_1 --run.steps 110000 --run.envs 1 --run.train_ratio 256 --run.log_every 250 --run.report_every 999999 --run.log_policy_video False --run.save_every 10000 --batch_size 16 --batch_length 64 --agent.hts.l_hier 0.3 --agent.report False --logger.outputs jsonl,scope,wandb --jax.prealloc False --jax.jit True 2>&1 | tee /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official/paper_artifacts/atari_v21_aux_warmup/run_logs/v21__hts_hier_x3_warmup100k__breakout__seed1.log
echo '===== DONE v21__hts_hier_x3_warmup100k__breakout__seed1 ====='
echo '===== START v21__hts_hier_x3_warmup100k__breakout__seed2 ====='
cd /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official && export CUDA_VISIBLE_DEVICES=5 WANDB_MODE=online WANDB_PROJECT=hts-wm-atari-dev WANDB_GROUP=v21_aux_warmup_breakout WANDB_JOB_TYPE=v21_stage_a_breakout_screen WANDB_TAGS=v21,aux_warmup,warmup100k,locked_hier_x3,atari100k,breakout,no_video WANDB_RUN_NAME=v21__hts_hier_x3_warmup100k__breakout__seed2 XLA_PYTHON_CLIENT_PREALLOCATE=false TMPDIR=/mnt/disk1/backup_user/dat.tt2/xuance/tmp; /mnt/disk1/backup_user/dat.tt2/xuance/.venv/bin/python -m dreamerv3.main_hts --configs hts_atari100k size12m hts_warmup_100k_raw --task atari100k_breakout --seed 2 --logdir /mnt/disk1/backup_user/dat.tt2/xuance/logs/external_baselines/dreamerv3_official_hts_v21_aux_warmup/hts_locked_hier_x3_warmup_100k_raw/breakout/seed_2 --run.steps 110000 --run.envs 1 --run.train_ratio 256 --run.log_every 250 --run.report_every 999999 --run.log_policy_video False --run.save_every 10000 --batch_size 16 --batch_length 64 --agent.hts.l_hier 0.3 --agent.report False --logger.outputs jsonl,scope,wandb --jax.prealloc False --jax.jit True 2>&1 | tee /mnt/disk1/backup_user/dat.tt2/xuance/external_baselines/dreamerv3-official/paper_artifacts/atari_v21_aux_warmup/run_logs/v21__hts_hier_x3_warmup100k__breakout__seed2.log
echo '===== DONE v21__hts_hier_x3_warmup100k__breakout__seed2 ====='
echo "V21 Stage A completed at $(date -Is)"
